labels: ['feature request']
body:
  - type: dropdown
    attributes:
      label: Impacted Product
      description: Which product does this idea relate to?
      options:
        - Dédale
    validations:
      required: true
  - type: textarea
    attributes:
      label: Goals
      description: Short list of what the feature request aims to address?
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Non-Goals
      description: Short list of what the feature request _does not_ aim to address?
      value: |
        1.
        2.
        3.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Background
      description: Discuss prior art, why do you think this feature is needed? Are there current alternatives?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposal
      description: How should this feature be implemented?
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Upvote and participation

        If you think this feature would be useful to your workflow, please consider to upvote this discussion.

        Don't hesitate to reply to this discussion with any of your ideas you would like to add to this topic.
