name: 'Docs Report'
description: Create a report for Bireme Lab documentation.
title: 'Docs: '
labels:
  - 'Documentation'
body:
  - type: markdown
    attributes:
      value: Thank you for helping us update our docs!
  - type: textarea
    attributes:
      label: What is the update you wish to see?
      description: 'Example: I would like to have more examples on how to create a new template using React Email'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Is there any context that might help us understand?
      description: A clear description of any added context that might help us understand.
    validations:
      required: true
  - type: input
    attributes:
      label: Does the docs page already exist? Please link to it.
      description: 'Example: https://en.doc.bireme.io/dedale/introduction'
    validations:
      required: false
