blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/orgs/bireme-lab/discussions
    about: Ask questions and discuss with other community members.
  - name: Feature request
    url: https://github.com/orgs/bireme-lab/discussions/new?category=ideas
    about: Feature or docs requests should be opened as discussions.
