import { Sprite } from "@/components/Icon/Icon";
import "@/styles/global.css";
import { cx } from "@/styles/mixins";
import { dark } from "@/styles/theme/dark.css";
import { GeistMono } from "geist/font/mono";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import { Gloria_Hallelujah } from "next/font/google";

const GloriaHallelujah = Gloria_Hallelujah({
  weight: "400",
  display: "swap",
  variable: "--font-gloria-hallelujah",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fr"
      className={cx(GeistSans.variable, GeistMono.variable, GloriaHallelujah.variable, dark)}
    >
      <head>
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#151515" />
        <meta name="apple-mobile-web-app-title" content="Bireme Lab" />
        <meta name="application-name" content="Bireme Lab" />
        <meta name="msapplication-TileColor" content="#151515" />
        <meta name="theme-color" content="#ffffff" />
      </head>
      <body>
        <Sprite />
        {children}
      </body>
    </html>
  );
}
